name: CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:

    - name: "Checking out"
      uses: actions/checkout@v4

    - name: "Setup java JDK"
      uses: actions/setup-java@v4.2.1
      with:
        java-version: 11
        distribution: temurin
        java-package: jdk
        cache: maven

    - name: "Run test"
      run: |
        mvn clean install
